# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/huellen/Desktop/wordle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/huellen/Desktop/wordle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/huellen/Desktop/wordle/CMakeFiles /Users/huellen/Desktop/wordle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/huellen/Desktop/wordle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wordle

# Build rule for target.
wordle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wordle
.PHONY : wordle

# fast build rule for target.
wordle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/build
.PHONY : wordle/fast

src/board/board.o: src/board/board.cpp.o
.PHONY : src/board/board.o

# target to build an object file
src/board/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/board/board.cpp.o
.PHONY : src/board/board.cpp.o

src/board/board.i: src/board/board.cpp.i
.PHONY : src/board/board.i

# target to preprocess a source file
src/board/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/board/board.cpp.i
.PHONY : src/board/board.cpp.i

src/board/board.s: src/board/board.cpp.s
.PHONY : src/board/board.s

# target to generate assembly for a file
src/board/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/board/board.cpp.s
.PHONY : src/board/board.cpp.s

src/cell/cell.o: src/cell/cell.cpp.o
.PHONY : src/cell/cell.o

# target to build an object file
src/cell/cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cell/cell.cpp.o
.PHONY : src/cell/cell.cpp.o

src/cell/cell.i: src/cell/cell.cpp.i
.PHONY : src/cell/cell.i

# target to preprocess a source file
src/cell/cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cell/cell.cpp.i
.PHONY : src/cell/cell.cpp.i

src/cell/cell.s: src/cell/cell.cpp.s
.PHONY : src/cell/cell.s

# target to generate assembly for a file
src/cell/cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cell/cell.cpp.s
.PHONY : src/cell/cell.cpp.s

src/cursor/cursor.o: src/cursor/cursor.cpp.o
.PHONY : src/cursor/cursor.o

# target to build an object file
src/cursor/cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cursor/cursor.cpp.o
.PHONY : src/cursor/cursor.cpp.o

src/cursor/cursor.i: src/cursor/cursor.cpp.i
.PHONY : src/cursor/cursor.i

# target to preprocess a source file
src/cursor/cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cursor/cursor.cpp.i
.PHONY : src/cursor/cursor.cpp.i

src/cursor/cursor.s: src/cursor/cursor.cpp.s
.PHONY : src/cursor/cursor.s

# target to generate assembly for a file
src/cursor/cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/cursor/cursor.cpp.s
.PHONY : src/cursor/cursor.cpp.s

src/game/game.o: src/game/game.cpp.o
.PHONY : src/game/game.o

# target to build an object file
src/game/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/game/game.cpp.o
.PHONY : src/game/game.cpp.o

src/game/game.i: src/game/game.cpp.i
.PHONY : src/game/game.i

# target to preprocess a source file
src/game/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/game/game.cpp.i
.PHONY : src/game/game.cpp.i

src/game/game.s: src/game/game.cpp.s
.PHONY : src/game/game.s

# target to generate assembly for a file
src/game/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/game/game.cpp.s
.PHONY : src/game/game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render/render.o: src/render/render.cpp.o
.PHONY : src/render/render.o

# target to build an object file
src/render/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/render/render.cpp.o
.PHONY : src/render/render.cpp.o

src/render/render.i: src/render/render.cpp.i
.PHONY : src/render/render.i

# target to preprocess a source file
src/render/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/render/render.cpp.i
.PHONY : src/render/render.cpp.i

src/render/render.s: src/render/render.cpp.s
.PHONY : src/render/render.s

# target to generate assembly for a file
src/render/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/render/render.cpp.s
.PHONY : src/render/render.cpp.s

src/row/row.o: src/row/row.cpp.o
.PHONY : src/row/row.o

# target to build an object file
src/row/row.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/row/row.cpp.o
.PHONY : src/row/row.cpp.o

src/row/row.i: src/row/row.cpp.i
.PHONY : src/row/row.i

# target to preprocess a source file
src/row/row.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/row/row.cpp.i
.PHONY : src/row/row.cpp.i

src/row/row.s: src/row/row.cpp.s
.PHONY : src/row/row.s

# target to generate assembly for a file
src/row/row.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wordle.dir/build.make CMakeFiles/wordle.dir/src/row/row.cpp.s
.PHONY : src/row/row.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wordle"
	@echo "... src/board/board.o"
	@echo "... src/board/board.i"
	@echo "... src/board/board.s"
	@echo "... src/cell/cell.o"
	@echo "... src/cell/cell.i"
	@echo "... src/cell/cell.s"
	@echo "... src/cursor/cursor.o"
	@echo "... src/cursor/cursor.i"
	@echo "... src/cursor/cursor.s"
	@echo "... src/game/game.o"
	@echo "... src/game/game.i"
	@echo "... src/game/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render/render.o"
	@echo "... src/render/render.i"
	@echo "... src/render/render.s"
	@echo "... src/row/row.o"
	@echo "... src/row/row.i"
	@echo "... src/row/row.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

